#!/usr/bin/env bash

TEXT="MRChem, a numerical real-space code for molecular electronic structure"
AUTHORS="Stig Rune Jensen, Luca Frediani, Peter Wind and contributors."

python .githooks/license_maintainer.py "$TEXT" "$AUTHORS"
