version: 2

variables:
  ubuntu-2204: &ubuntu-2204
    docker:
      - image: ghcr.io/mrchemsoft/metamr/circleci_ubuntu-22.04:sha-9f6ecd4
        name: tsubame
        user: merzbow
    working_directory: ~/mrchem
  configure-serial: &configure-serial
    run:
      name: Configuring serial
      shell: /bin/bash
      command: |
        python setup \
          --type=release \
          --cxx=g++ \
          --prefix=$HOME/Software/MRChem
  configure-omp: &configure-omp
    run:
      name: Configuring OpenMP parallel
      shell: /bin/bash
      command: |
        python setup \
          --type=release \
          --cxx=g++ \
          --omp \
          --prefix=$HOME/Software/MRChem-omp
  configure-mpi: &configure-mpi
    run:
      name: Configuring MPI parallel
      shell: /bin/bash
      command: |
        python setup \
          --type=release \
          --cxx=mpicxx \
          --mpi \
          --prefix=$HOME/Software/MRChem-mpi
  build: &build
    run:
      name: Building and installing
      shell: /bin/bash
      command: |
        cmake --build build --target install -- VERBOSE=1
  tests: &tests
    run:
      name: Testing
      shell: /bin/bash
      command: |
        cd build
        ctest --output-on-failure --verbose

jobs:
  serial-py3:
    <<: *ubuntu-2204
    steps:
      - checkout
      - *configure-serial
      - *build
      - *tests
  omp-py3:
    <<: *ubuntu-2204
    environment:
      - OMP_NUM_THREADS: '2'
    steps:
      - checkout
      - *configure-omp
      - *build
      - *tests
  mpi-py3:
    <<: *ubuntu-2204
    steps:
      - checkout
      - *configure-mpi
      - *build
      - *tests

workflows:
  version: 2
  build:
    jobs:
      - serial-py3
      - omp-py3
      - mpi-py3
