#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))

from runtest import cli, get_filter, run, version_info  # isort:skip
from runtest_config import configure  # isort:skip

assert version_info.major == 2

f = [
    get_filter(string='Sum orbital energy:',           rel_tolerance=1.0e-6),
    get_filter(string='Kinetic energy:',               rel_tolerance=1.0e-6),
    get_filter(string='E-N energy:',                   rel_tolerance=1.0e-6),
    get_filter(string='Coulomb energy:',               rel_tolerance=1.0e-6),
    get_filter(string='Exchange energy:',              rel_tolerance=1.0e-6),
    get_filter(string='X-C energy:',                   rel_tolerance=1.0e-6),
    get_filter(string='El. external field energy:',    rel_tolerance=1.0e-6),
    get_filter(string='Nuc. external field energy:',   abs_tolerance=1.0e-6),
    get_filter(string='Electronic energy:',            rel_tolerance=1.0e-6),
    get_filter(string='Total energy       (au)',       rel_tolerance=1.0e-6),
    get_filter(string='                   (kJ/mol)',   rel_tolerance=1.0e-6),
    get_filter(string='                   (kcal/mol)', rel_tolerance=1.0e-6),
    get_filter(string='                   (eV)',       rel_tolerance=1.0e-6),
    get_filter(string='(Debye)',                       abs_tolerance=1.0e-6),
]

options = cli()

ierr = 0
ierr += run(
    options, configure, input_files=['mrchem.inp'], filters={'stdout': f})

sys.exit(ierr)
